enum actionTypes{
    GET_USER_CONTACTS="GET_USER_CONTACTS",
    FAILED="FAILED",
   LOADING="LOADING",
//    DELETE_USER="DELETE_USER",
   ADD_USER_CONTACTS="ADD_USER_CONTACTS"
}

export default actionTypes