enum actionTypes{
    GET_USER_CONTACTS="GET_USER_CONTACTS",
    FAILED="FAILED",
   LOADING="LOADING",
   DELETE_SOCIAL="DELETE_SOCIAL",
   ADD_USER_CONTACTS="ADD_USER_CONTACTS",
   SINGLE_SOCIAL=" SINGLE_SOCIAL"
}

export default actionTypes